<?php

namespace App\DataFixtures;

use App\Entity\Artisan;
use App\Entity\Crm;
use App\Entity\MediaObject;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Faker\Factory;

class ArtisanFixtures extends Fixture
{
    private static $metiers = [
        "Meunier",
        "Transformateur et conservateur de fruits",
        "légumes",
        "noix et feuilles",
        "Fabricant de condiments et assaisonnements",
        "Transformateur de grains et de tubercules",
        "Fabricant de produits amylacés",
        "Fabricant d’huiles et de graisses brutes",
        "raffinées et comestibles",
        "Boucher",
        "Charcutier",
        "Transformateur et conservateurs de viande et de volailles ",
        "Préparateur de produits à base de viande",
        "Transformateur et conservateur de poissons",
        "Transformateur et conservateur de crustacées et de mollusques",
        "Fabricant de produits laitiers ",
        "Fabricant de glaces alimentaires ",
        "Fabricant de beurre",
        "Fabricant de fromage",
        "Fabricant de beurre de karité",
        "Fabricant de boissons artisanales à base de fruits, de légumes, de céréales et de tubercules",
        "Fabricant d’eau de boisson",
        "Préparateur de jus fruits et légumes,",
        "Fabricant d’autres produits alimentaires",
        "Boulanger",
        "Boulanger-pâtissier",
        "Pâtissier",
        "Biscuitier",
        "Fabricant de friandises à base d’arachide, de sucre caramélé, de miel (apiculteurs), de pâtes alimentaires",
        "Restaurateur",
        "Traiteur",
        "Cuisinier et métiers connexes",
        "Fabricant de plats préparés",
        "Fabricant de galettes, de beignets et d’autres produits alimentaires",
        "Fabricant de sels",
        "Fabricant d’aliments pour animaux",
        "Fabricant d’engrais organiques",
        "Transformateur de déchets organiques",
        "Orpailleur traditionnels ",
        "Extracteur de produits de carrières",
        "Extracteur d’argiles",
        "Extracteur de minéraux chimiques ",
        "Extracteur d’engrais minéraux",
        "Producteur de sel et autres activités extractives ",
        "Puisatier et autres spécialistes d’activités de forage",
        "Tailleur de pierres",
        "Fondeur de pierres",
        "Marbrier",
        "Briquetier",
        "Bétonnier",
        "Tuilier et autres ",
        "Fabricant de matériaux de construction",
        "Maçon",
        "Spécialiste en réhabilitation de bâtiments ",
        "Constructeur de cases",
        "Constructeur d’ouvrages d’art",
        "Aménagiste de chaussée",
        "Poseur de pavés",
        "Charpentier",
        "Coffreur",
        "Plombier",
        "Carreleur",
        "Poseur d’enduits",
        "Spécialiste en revêtement ",
        "Spécialiste en étanchéité, ",
        "Vitrier",
        "Miroitier",
        "Ferrailleur bâtiment",
        "Plâtrier",
        "Décorateur-staffeur",
        "Peintre bâtiment",
        "Électriciens bâtiment",
        "Dessinateurs bâtiment",
        "Autres spécialistes de travaux spécialisés",
        "Forgeron",
        "Chaudronnier",
        "Métallurgiste",
        "Ferrailleur",
        "Tourneur",
        "Fraiseur",
        "Affûteur",
        "Fabricant de matériels et équipements agricoles et forestiers",
        "Fondeur",
        "Outilleur",
        "Fabricant de mobilier en fer forgé",
        "Menuisier métalliques",
        "Menuisier aluminium ",
        "Tréfileur",
        "Modeleur sur métaux",
        "Soudeur",
        "Réparateur et mécanicien de véhicules ",
        "Réparateur et mécanicien cycles",
        "Réparateur et mécanicien cyclomoteurs",
        "Réparateur de pompe hydraulique",
        "Carrossier (Tôliers)",
        "Peintre engins",
        "Vulcanisateur",
        "Électricien automobiles",
        "Électronicien",
        "Mécatronicien",
        "Ajusteur d’appareils électriques",
        "Fabricant de machines et matériels agricoles",
        "Réparateur de matériels de transport fluvial et naval",
        "Conducteur de taxis compteurs ",
        "Conducteur de VTC",
        "Conducteur de taxis communaux",
        "Conducteur de taxis motos",
        "Livreur ",
        "Conducteur de charrette",
        "Conducteur de pirogues ",
        "Conducteur de pousse-pousse",
        "Docker",
        "Service de déménagement",
        "Réparateur d’ordinateurs et d’équipements périphériques, d’équipements de communication",
        "Horloger",
        "Installateur et réparateurs d’appareils médicaux",
        "Opticien et réparateur de lunettes",
        "Fabricant et réparateurs de machines-outils",
        "Fabricant et réparateurs de petit outillage",
        "Fabricant et réparateurs d’équipements de foyers",
        "Fabricant et réparateurs d’articles de sport",
        "Serrurier",
        "Fabricant et réparateur d’appareils de haute précision",
        "Spécialiste en froid climatisation",
        "Rebobineur",
        "Réparateur d’appareils électriques",
        "Menuisier bois",
        "Ébéniste",
        "Bucheron",
        "Charbonnier",
        "Scieur de bois ",
        "Constructeur de pirogues et embarcations",
        "Fabricant de tam-tam",
        "Fabricant d’instruments de musique en bois",
        "Sculpteur sur bois, objets divers à base de bois",
        "Fabricant d’articles en liège",
        "Fabricant d’articles en sparterie",
        "Fabricant d’objets en fibres végétales",
        "Fabricant d’articles en pailles",
        "Menuisier sur bambous, rônier et rotin",
        "Menuisier de meubles divers à base de végétaux",
        "Fabricant de mortiers",
        "Filateur",
        "Tisserand",
        "Tailleur",
        "Couturier",
        "Brodeur",
        "Stoppeur",
        "Modéliste-styliste",
        "Fabricant d’objets et accessoires en tissu",
        "Teinturier",
        "Sérigraphe sur tissu",
        "Tapissier",
        "Fabricant d’articles à mailles et d’autres textiles",
        "Fabricant de vêtements",
        "Fabricant d’accessoires en cuir",
        "Fabricant d’articles de fourrure",
        "Fabricant de tentes ",
        "Fabricant de voiles",
        "Fabricant de filets de pêche",
        "Taxidermiste",
        "Tanneur",
        "Cordonnier",
        "Maroquinier",
        "Bottier",
        "Sellier",
        "Gainier",
        "Relieur",
        "Cireur de chaussures",
        "Graveur sur cuir",
        "Photographe",
        "Cameraman",
        "Maquettiste",
        "Graveur",
        "Imprimeur",
        "Encadreur et assimilés",
        "Installateur/réparateur de matériel audiovisuel",
        "Installateur/réparateur photographique",
        "Installateur/réparateur cinématographique",
        "Installateur/réparateur de télécommunication et assimilés",
        "Électricien cinéma",
        "Coiffeur",
        "Tresseuse",
        "Esthéticien",
        "Fabricant de savons",
        "Fabricant de parfums ",
        "Fabricant de produits chimiques",
        "Fabricant de cosmétiques et assimilés",
        "Spécialiste en soins de beauté",
        "Préparateur de pharmacopée traditionnelle",
        "Fabricant de prothèses et matériels orthopédiques",
        "Blanchisseur",
        "Spécialiste en pressing",
        "Lavandier",
        "Laveur de voitures",
        "Spécialiste en nettoyage courant de locaux et",
        "autres services de nettoyage",
        "Spécialiste en traitement et élimination des déchets ",
        "Bijoutier",
        "Orfèvre",
        "Joaillier",
        "Bronzier",
        "Ferronnier d’art",
        "Armurier",
        "Perlier",
        "Sculpteur et décorateur sur tous matériaux",
        "Fabricant de jeux ",
        "Fabricant de jouets ",
        "Fabricant d’instruments de musique,",
        "Spécialiste en taille, façonnage et finition d’objets d’art",
        "Potier",
        "Céramiste",
        "Verrier et autres objets d’art",
        "Fabricant en art graphique",
        "Fabricant en art floral",
        "Fabricant d’objets de décoration d’intérieur,",
        "Jardinier",
        "Créateur d’espaces verts",
        "Paysagiste",
        "Aménagiste"
    ];
    private static $villes = [
        "abengourou",
        "abidjan",
        "aboisso",
        "abongoua",
        "adaou",
        "adiake",
        "adjouan",
        "adzope",
        "agboville",
        "agnibilekrou",
        "akoupe",
        "alepe",
        "ananda",
        "annepe",
        "anyama",
        "appimadoum",
        "attinguié",
        "bacanda",
        "badikaha",
        "bako",
        "bangolo",
        "becouefin",
        "bedi-goazon",
        "beoumi",
        "bettie",
        "biankouma",
        "bieby",
        "bingerville",
        "bin-houye",
        "blapleu",
        "blenimeouin",
        "blessegue",
        "blolequin",
        "boahia",
        "bocanda",
        "bogouine",
        "bondoukou",
        "bongouanou",
        "bonoua",
        "bouafle",
        "bouake",
        "bouandougou",
        "bouna",
        "boundiali",
        "brofodoume",
        "dabakala",
        "dabou",
        "dabouyo",
        "daloa",
        "danane",
        "daoukro",
        "diamarakro",
        "dianra",
        "diawalla",
        "diboke",
        "didievi",
        "dignago",
        "dimbokro",
        "divo",
        "doke",
        "doudoukou",
        "duekoue",
        "fadiadougou",
        "famienkro",
        "ferkessedougou",
        "gagnoa",
        "gbangbegouine",
        "gbangbegouine-yati",
        "gohouo-zagna",
        "gomon",
        "gouine",
        "grand-bassam",
        "grand-lahou",
        "guessabo",
        "guiberoua",
        "gueyo",
        "guinglo-tahouake",
        "guitry",
        "hire",
        "issia",
        "jacqueville",
        "kahin-zarabaon",
        "kani",
        "kanzra",
        "katiola",
        "kong",
        "korhogo",
        "koro",
        "kouakro",
        "kounahiri",
        "koun-fao",
        "kouto",
        "koutouba",
        "kpata",
        "lakota",
        "lolobo",
        "loviguie",
        "mamini",
        "man",
        "mankono",
        "mantongouine",
        "marahoue",
        "m'bahiakro",
        "m'batto",
        "morondo",
        "nafana (prikro)",
        "n'douci",
        "n'gokro",
        "niakaramandougou",
        "niambezaria",
        "nielle",
        "nofou",
        "odienne",
        "oume",
        "ouyably-gnondrou",
        "pacobo",
        "pehe",
        "sakassou",
        "samatiguila",
        "sandougou-soba",
        "san-pedro",
        "sassandra",
        "seguela",
        "sinfra",
        "soubre",
        "tabou",
        "tafire",
        "taï",
        "tanda",
        "tiagba",
        "tiapoum",
        "tiassale",
        "tiebissou",
        "tiedio",
        "tieningboue",
        "tingrela",
        "tinhou",
        "tiobli",
        "togoniere",
        "touba",
        "tougbo",
        "toulepleu",
        "toumodi",
        "toumoukoro",
        "vavoua",
        "varale",
        "yakasse-me",
        "yamoussoukro",
        "yaou",
        "yorodougou",
        "zonneu",
        "zouan-hounien"
    ];
    private static $pays = [
        "Afghanistan",
        "Afrique du Sud",
        "Albanie",
        "Algérie",
        "Allemagne",
        "Andorre",
        "Angola",
        "Antigua-et-Barbuda",
        "Arabie saoudite",
        "Argentine",
        "Arménie",
        "Australie",
        "Autriche",
        "Azerbaïdjan",
        "Bahamas",
        "Bahreïn",
        "Bangladesh",
        "Barbade",
        "Belgique",
        "Belize",
        "Bénin",
        "Bhoutan",
        "Biélorussie",
        "Birmanie",
        "Bolivie",
        "Bosnie-Herzégovine",
        "Botswana",
        "Brésil",
        "Brunei",
        "Bulgarie",
        "Burkina Faso",
        "Burundi",
        "Cambodge",
        "Cameroun",
        "Canada",
        "Cap-Vert",
        "Chili",
        "Chine",
        "Chypre",
        "Colombie",
        "Comores",
        "Congo-Brazzaville",
        "Congo-Kinshasa",
        "Corée du Nord",
        "Corée du Sud",
        "Costa Rica",
        "Côte d’Ivoire",
        "Croatie",
        "Cuba",
        "Danemark",
        "Djibouti",
        "Dominique",
        "Égypte",
        "Émirats arabes unis",
        "Équateur",
        "Érythrée",
        "Espagne",
        "Estonie",
        "Eswatini",
        "États-Unis",
        "Éthiopie",
        "Fidji",
        "Finlande",
        "France",
        "Gabon",
        "Gambie",
        "Géorgie",
        "Ghana",
        "Grèce",
        "Grenade",
        "Guatemala",
        "Guinée",
        "Guinée équatoriale",
        "Guinée-Bissau",
        "Guyana",
        "Haïti",
        "Honduras",
        "Hongrie",
        "Inde",
        "Indonésie",
        "Irak",
        "Iran",
        "Irlande",
        "Islande",
        "Israël",
        "Italie",
        "Jamaïque",
        "Japon",
        "Jordanie",
        "Kazakhstan",
        "Kenya",
        "Kirghizistan",
        "Kiribati",
        "Kosovo",
        "Koweït",
        "Laos",
        "Lesotho",
        "Lettonie",
        "Liban",
        "Libéria",
        "Libye",
        "Liechtenstein",
        "Lituanie",
        "Luxembourg",
        "Macédoine du Nord",
        "Madagascar",
        "Malaisie",
        "Malawi",
        "Maldives",
        "Mali",
        "Malte",
        "Maroc",
        "Îles Marshall",
        "Maurice",
        "Mauritanie",
        "Mexique",
        "Micronésie",
        "Moldavie",
        "Monaco",
        "Mongolie",
        "Monténégro",
        "Mozambique",
        "Namibie",
        "Nauru",
        "Népal",
        "Nicaragua",
        "Niger",
        "Nigéria",
        "Norvège",
        "Nouvelle-Zélande",
        "Oman",
        "Ouganda",
        "Ouzbékistan",
        "Pakistan",
        "Palaos",
        "Palestine",
        "Panama",
        "Papouasie-Nouvelle-Guinée",
        "Paraguay",
        "Pays-Bas",
        "Pérou",
        "Philippines",
        "Pologne",
        "Portugal",
        "Qatar",
        "République centrafricaine",
        "République tchèque",
        "Roumanie",
        "Royaume-Uni",
        "Russie",
        "Rwanda",
        "Saint-Kitts-et-Nevis",
        "Sainte-Lucie",
        "Saint-Marin",
        "Saint-Vincent-et-les-Grenadines",
        "Salvador",
        "Samoa",
        "Sao Tomé-et-Principe",
        "Sénégal",
        "Serbie",
        "Seychelles",
        "Sierra Leone",
        "Singapour",
        "Slovaquie",
        "Slovénie",
        "Somalie",
        "Soudan",
        "Soudan du Sud",
        "Sri Lanka",
        "Suède",
        "Suisse",
        "Suriname",
        "Syrie",
        "Tadjikistan",
        "Tanzanie",
        "Tchad",
        "Thaïlande",
        "Timor oriental",
        "Togo",
        "Tonga",
        "Trinité-et-Tobago",
        "Tunisie",
        "Turkménistan",
        "Turquie",
        "Tuvalu",
        "Ukraine",
        "Uruguay",
        "Vanuatu",
        "Vatican",
        "Venezuela",
        "Viêt Nam",
        "Yémen",
        "Zambie",
        "Zimbabwe"
    ];
    private static $nationalites = [
        "afghan (e)",
        "albanais (e)",
        "algérien (e)",
        "allemand (e)",
        "americain (e)",
        "andorran (e)",
        "angolais (e)",
        "antiguaise-et-barbudien (e)",
        "argentin (e)",
        "armenien (e)",
        "australien (e)",
        "autrichien (e)",
        "azerbaïdjanais (e)",
        "bahamien (e)",
        "bahreinien (e)",
        "bangladais (e)",
        "barbadien (e)",
        "belge",
        "belizien (e)",
        "béninois (e)",
        "bhoutanais (e)",
        "biélorusse",
        "birman (e)",
        "bissau-guinéen (e)",
        "bolivien (e)",
        "bosnien (e)",
        "botswanais (e)",
        "brésilien (e)",
        "britannique",
        "brunéien (e)",
        "bulgare",
        "burkinabé (e)",
        "burundais (e)",
        "cambodgien (e)",
        "camerounais (e)",
        "canadien (e)",
        "cap-verdien (e)",
        "centrafricain (e)",
        "chilien (e)",
        "chinois (e)",
        "chypriote (e)",
        "colombien (e)",
        "comorien (e)",
        "congolais (e)",
        "congolais (e)",
        "cookienn (e)",
        "costaricain (e)",
        "croate",
        "cubain (e)",
        "danois (e)",
        "djiboutien (e)",
        "dominicain (e)",
        "dominiquais (e)",
        "égyptien (e)",
        "émirien (e)",
        "équato-guineen (e)",
        "équatorien (e)",
        "érythréen (e)",
        "espagnol (e)",
        "est-timorais (e)",
        "estonien (e)",
        "éthiopien (e)",
        "fidjien (e)",
        "finlandais (e)",
        "français (e)",
        "gabonais (e)",
        "gambien (e)",
        "georgien (e)",
        "ghanéen (e)",
        "grenadien (e)",
        "guatémaltèque",
        "guinéen (e)",
        "guyanien (e)",
        "haïtien (e)",
        "hellénique",
        "hondurien (e)",
        "hongrois (e)",
        "indien (e)",
        "indonésien (e)",
        "irakien (e)",
        "iranien (e)",
        "irlandais (e)",
        "islandais (e)",
        "israélien (e)",
        "italien (e)",
        "ivoirien (e)",
        "jamaïcain (e)",
        "japonais (e)",
        "jordanien (e)",
        "kazakhstanais (e)",
        "kenyan (e)",
        "kirghize",
        "kiribatien (e)",
        "kittitien et névicien (e)",
        "koweïtien (e)",
        "laotien (e)",
        "lesothan (e)",
        "letton (e)",
        "libanais (e)",
        "libérien (e)",
        "libyen (e)",
        "liechtensteinois (e)",
        "lituanien (e)",
        "luxembourgeois (e)",
        "macédonien (e)",
        "malaisien (e)",
        "malawien (e)",
        "maldivien (e)",
        "malgache",
        "malien (e)",
        "maltais (e)",
        "marocain (e)",
        "marshallais (e)",
        "mauricien (e)",
        "mauritanien (e)",
        "mexicain (e)",
        "micronésien (e)",
        "moldave",
        "monegasque",
        "mongolien (e)",
        "monténégrin (e)",
        "mozambicain (e)",
        "namibien (e)",
        "nauruan (e)",
        "néerlandais (e)",
        "néo-zélandaise (e)",
        "népalais (e)",
        "nicaraguayen (e)",
        "nigérian (e)",
        "nigérien (e)",
        "niuéen (e)",
        "nord-coréen (e)",
        "norvégien (e)",
        "omanais (e)",
        "ougandais (e)",
        "ouzbék (e)",
        "pakistanais (e)",
        "palaosien (e)",
        "palestinien (e)",
        "panaméen (e)",
        "papouane-néo-guinéen (e)",
        "paraguayen (e)",
        "péruvien (e)",
        "philippien (e)",
        "polonais (e)",
        "portugais (e)",
        "qatarien (e)",
        "roumain (e)",
        "russe",
        "rwandais (e)",
        "saint-lucienn (e)",
        "saint-marinais (e)",
        "saint-vincentais (e) et grenadine",
        "salomonais (e)",
        "salvadorien (e)",
        "samoan (e)",
        "santoméen (e)",
        "saoudien (e)",
        "sénégalais (e)",
        "serbe",
        "seychellois (e)",
        "sierra-léonais (e)",
        "singapourien (e)",
        "slovaque",
        "slovène",
        "somalien (e)",
        "soudanais (e)",
        "sri-lankais (e)",
        "sud-africain (e)",
        "sud-coréen (e)",
        "sud-soudanais (e)",
        "suédois (e)",
        "suisse",
        "surinamais (e)",
        "swazie",
        "syrien (e)",
        "tadjik (e)",
        "tanzanien (e)",
        "tchadien (e)",
        "tchèque",
        "thaïlandais (e)",
        "togolais (e)",
        "tonguien (e)",
        "trinidadien (e)",
        "tunisien (e)",
        "turkmène",
        "turque",
        "tuvaluan (e)",
        "ukrainien (e)",
        "uruguayen (e)",
        "vanuatuan (e)",
        "vatican (e)",
        "vénézuélien (e)",
        "vietnamien (e)",
        "yéménite",
        "zambien (e)",
        "zimbabwéen (e)"
    ];
    private static $communes = [
        "abengourou",
        "abidjan",
        "aboisso",
        "abongoua",
        "adaou",
        "adiake",
        "adjouan",
        "adzope",
        "agboville",
        "agnibilekrou",
        "akoupe",
        "alepe",
        "ananda",
        "annepe",
        "anyama",
        "appimadoum",
        "attinguié",
        "bacanda",
        "badikaha",
        "bako",
        "bangolo",
        "becouefin",
        "bedi-goazon",
        "beoumi",
        "bettie",
        "biankouma",
        "bieby",
        "bingerville",
        "bin-houye",
        "blapleu",
        "blenimeouin",
        "blessegue",
        "blolequin",
        "boahia",
        "bocanda",
        "bogouine",
        "bondoukou",
        "bongouanou",
        "bonoua",
        "bouafle",
        "bouake",
        "bouandougou",
        "bouna",
        "boundiali",
        "brofodoume",
        "dabakala",
        "dabou",
        "dabouyo",
        "daloa",
        "danane",
        "daoukro",
        "diamarakro",
        "dianra",
        "diawalla",
        "diboke",
        "didievi",
        "dignago",
        "dimbokro",
        "divo",
        "doke",
        "doudoukou",
        "duekoue",
        "fadiadougou",
        "famienkro",
        "ferkessedougou",
        "gagnoa",
        "gbangbegouine",
        "gbangbegouine-yati",
        "gohouo-zagna",
        "gomon",
        "gouine",
        "grand-bassam",
        "grand-lahou",
        "guessabo",
        "guiberoua",
        "gueyo",
        "guinglo-tahouake",
        "guitry",
        "hire",
        "issia",
        "jacqueville",
        "kahin-zarabaon",
        "kani",
        "kanzra",
        "katiola",
        "kong",
        "korhogo",
        "koro",
        "kouakro",
        "kounahiri",
        "koun-fao",
        "kouto",
        "koutouba",
        "kpata",
        "lakota",
        "lolobo",
        "loviguie",
        "mamini",
        "man",
        "mankono",
        "mantongouine",
        "marahoue",
        "m'bahiakro",
        "m'batto",
        "morondo",
        "nafana (prikro)",
        "n'douci",
        "n'gokro",
        "niakaramandougou",
        "niambezaria",
        "nielle",
        "nofou",
        "odienne",
        "oume",
        "ouyably-gnondrou",
        "pacobo",
        "pehe",
        "sakassou",
        "samatiguila",
        "sandougou-soba",
        "san-pedro",
        "sassandra",
        "seguela",
        "sinfra",
        "soubre",
        "tabou",
        "tafire",
        "taï",
        "tanda",
        "tiagba",
        "tiapoum",
        "tiassale",
        "tiebissou",
        "tiedio",
        "tieningboue",
        "tingrela",
        "tinhou",
        "tiobli",
        "togoniere",
        "touba",
        "tougbo",
        "toulepleu",
        "toumodi",
        "toumoukoro",
        "vavoua",
        "varale",
        "yakasse-me",
        "yamoussoukro",
        "yaou",
        "yorodougou",
        "zonneu",
        "zouan-hounien"
    ];

    private static $sexe= [
        'F',
        'H'
    ];
    private static $maritalStatus= [
        'Marié',
        'Veuf(ve)',
        'Divorcé'
    ];

    protected $faker;

    public function load(ObjectManager $manager): void
    {
        $photos = [];
        $crms = [];

        $this->faker = Factory::create();

        $mediaObjects = $manager->getRepository(MediaObject::class)->findAll();
        foreach ($mediaObjects as $photoArtisan) {
            $photos[] = $photoArtisan;
        }

        $crmObjects = $manager->getRepository(Crm::class)->findAll();
        foreach ($crmObjects as $crm) {
            $crms[] = $crm;
        }

        for ($i = 0; $i < 2; $i++) {
            $artisan = new Artisan();
            $artisan->setPhoto('/artisans/' . $this->faker->randomElement($photos));
            $artisan->setNom($this->faker->lastName());
            $artisan->setPrenoms($this->faker->firstName);
            $artisan->setPrenoms($this->faker->randomElement(self::$sexe));
            $artisan->setEmail($this->faker->email);
            $artisan->setCategory($this->faker->word);
            $artisan->setDomicile($this->faker->randomElement(self::$communes));
            $artisan->setEtatCivil($this->faker->randomElement(self::$maritalStatus));

            $artisan->setDateNaissance(new \DateTime($this->faker->date('Y-m-d')));
            $artisan->setDrivingLicenseNumber(new \DateTime($this->faker->date('Y-m-d')));
            $artisan->setDateNaissance(new \DateTime($this->faker->date('Y-m-d')));

            $artisan->setActiviteExercee($this->faker->word);
            $artisan->setActiviteExerceeLieu($this->faker->city());
            $artisan->setActivitePrincipale($this->faker->name);
            $artisan->setActiviteSecondaire($this->faker->name);

            $artisan->setNumeroPieceIdentite($this->faker->randomNumber(10));
            $artisan->setAutoriteDelivrancePieceIdentite('ONECI');
            $artisan->setDateDelivrancePieceIdentite($this->faker->dateTimeBetween('-10 years', 'now'));

            $artisan->setCnps($this->faker->randomNumber(10));
            $artisan->setLatitude($this->faker->latitude());
            $artisan->setLongitude($this->faker->longitude());

            $artisan->setCreatedAt(new \DateTime());
            $artisan->setDateNaissance(new \DateTime($this->faker->date('Y-m-d')));

            $artisan->setFormationApprentissageMetier($this->faker->word);
            $artisan->setFormationApprentissageMetierNiveau($this->faker->numberBetween(0,3));
            $artisan->setFormationApprentissageMetierDiplome($this->faker->word);

            $artisan->setNationalite($this->faker->randomElement(self::$nationalites));
            $artisan->setNumeroRM($this->faker->randomNumber(10));
            $artisan->setPaysNaissance($this->faker->randomElement(self::$pays));

            $artisan->setCrm($this->faker->randomElement($crms));

            $manager->persist($artisan);
        }

        $manager->flush();
    }

    public static function getGroups(): array
    {
        return ['artisan'];
    }

}
