version: '3.8'

services:

  db:
    image: mariadb:10.5
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: QT6e5APtSYaU
      MYSQL_USER: root
      MYSQL_PASSWORD: QT6e5APtSYaU
      MYSQL_DATABASE: siga_db
    volumes:
      - ./db:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      UPLOAD_LIMIT: 300M
    ports:
      - "83:80"

  app:
    container_name: app
    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile-prod
    depends_on:
      - db
    environment:
      - APP_ENV=prod
      - TZ=Africa/Abidjan
      - MAILER_DSN=gmail+smtp://anguidev@gmail.com:jotkgdyyfrlujfza@default
      - DATABASE_URL=mysql://root:QT6e5APtSYaU@db:3306/siga_db?serverVersion=10.5.27&charset=utf8mb4
    volumes:
      - ./codebase:/var/www/html

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - ./codebase:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "82:80"
    depends_on:
      - app