version: '3.8'

networks:
  internal:
  proxy:
    external: true

services:

  traefik:
    image: "traefik:2.11"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
#     - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy

  db:
    image: mariadb:10.5
    container_name: db
    restart: always
    labels:
      - "traefik.enable=false"
    environment:
      MYSQL_ROOT_PASSWORD: QT6e5APtSYaU
      MYSQL_USER: root
      MYSQL_PASSWORD: QT6e5APtSYaU
      MYSQL_DATABASE: siga_db
    volumes:
      - ./db:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - 3306:3306
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.sigaci.develop`)"
    environment:
      UPLOAD_LIMIT: 300M
#    ports:
#      - "83:80"
    networks:
      - internal
      - proxy

  app:
    container_name: app
    restart: always
    build:
      context: ./docker
    depends_on:
      - db
    labels:
      - "traefik.enable=false"
    environment:
      - APP_ENV=dev
      - XDEBUG_MODES=debug
      - TZ=Africa/Abidjan
      - MAILER_DSN=gmail+smtp://anguidev@gmail.com:jotkgdyyfrlujfza@default
      - DATABASE_URL=mysql://root:QT6e5APtSYaU@db:3306/siga_db?serverVersion=10.5.27&charset=utf8mb4
      - REMOTE_HOST=host.docker.internal
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/var/www/html
    networks:
      - internal

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.mailpit.rule=Host(`smtp.sigaci.develop`)"
    volumes:
      - ./data/smtp_data:/data
#    ports:
#      - "8025:8025"
#      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_UI_AUTH: "anguidev:6fkMpt4P4d7d"
    networks:
      - internal

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.www.rule=Host(`sigaci.develop`)"
      - "traefik.http.services.www.loadbalancer.server.port=80"
#    ports:
#      - "82:80"
    depends_on:
      - app
    networks:
      - internal
      - proxy

