<?php
namespace App\Service\Artisan;
enum StatutArtisan: string
{
    case ENROLEMENT_PHOTO_DOCUMENT_SCANNE = 'ENROLEMENT_PHOTO_DOCUMENT_SCANNE';
    case ENROLEMENT_DONNEES_COMPLETES = 'ENROLEMENT_DONNEE_COMPLETES';
    case ENROLEMENT_PAYEMENT_FRAIS_ENROLEMENT = 'ENROLEMENT_PAYEMENT_FRAIS_ENROLEMENT';
    case ENROLEMENT_VERIFICATION_DONNEE = 'ENROLEMENT_VERIFICATION_DONNEE';
    case ENROLEMENT_PAIEMENT_VALIDER_CNMCI = 'ENROLEMENT_PAIEMENT_VALIDER_CNMCI';
    case ENROLEMENT_PAIEMENT_REJETE_CNMCI = 'ENROLEMENT_PAIEMENT_REJETE_CNMCI';
    case ENROLEMENT_REJETE_CNMCI = 'ENROLEMENT_REJETE_CNMCI';
    case ENROLEMENT_VALIDER_CNMCI = 'ENROLEMENT_VALIDER_CNMCI';
    case ENROLEMENT_EN_ATTENTE_PRODUCTION_CARTE = 'ENROLEMENT_EN_ATTENTE_PRODUCTION_CARTE';

}