# traefik/dynamic_conf.yml
# Dynamic configuration for Traefik (e.g., HTTP to HTTPS redirect)

http:
  # Redirect all HTTP traffic to HTTPS
  routers:
    http-catchall:
      entryPoints:
        - "web"
      rule: "HostRegexp(`{host:.+}`)" # Match all hosts
      middlewares:
        - "redirect-to-https" # Apply the redirect middleware
      service: "noop@internal" # Internal dummy service

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: "https" # Redirect to HTTPS
        permanent: true # Use a permanent redirect (301)
