# traefik/traefik.yml
# Static configuration for Traefik

# Entrypoints define the ports Traefik listens on
entryPoints:
  web:
    address: ":80" # HTTP entrypoint
    # Redirect HTTP to HTTPS (dynamic configuration will handle this)
  websecure:
    address: ":443" # HTTPS entrypoint

# API and Dashboard configuration
api:
  dashboard: true # Enable the Traefik dashboard
  insecure: true # Allow insecure access to the dashboard (for development only)

# Providers tell Traefik where to find its configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock" # Connect to Docker daemon
    exposedByDefault: false # Only services with traefik.enable=true will be exposed
    network: web # Specify the network Traefik should listen on for Docker services
  file:
    filename: /etc/traefik/dynamic_conf.yml # Path to dynamic configuration file
    watch: true # Watch for changes in the dynamic config file

# Certificates Resolvers for Let's Encrypt
certificatesResolvers:
  letsencrypt:
    acme:
      email: anguidev@gmail.com # IMPORTANT: Replace with your actual email
      storage: /etc/traefik/acme.json # Path to store certificates
      # Use TLS challenge for automatic certificate issuance
      tlsChallenge: {}
      # Use Let's Encrypt staging environment for testing (comment out for production)
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      # For production, use:
      # caServer: "https://acme-v02.api.letsencrypt.org/directory"
