# traefik/traefik.yml
# Static configuration for Traefik

# Entrypoints definition
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"

# Providers definition
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false # Only expose containers that have traefik.enable=true label

# Certificates Resolvers definition (for Let's Encrypt)
certificatesResolvers:
  le:
    acme:
      email: "anguidev@gmail.com" # IMPORTANT: Change to your actual email
      storage: "/etc/traefik/acme.json"
      tlsChallenge: {} # Use TLS challenge for ACME

# API and Dashboard configuration
api:
  dashboard: true
  insecure: true # IMPORTANT: Set to false in production for security

# Log configuration
log:
  level: INFO # DEBUG, INFO, WARNING, ERROR, FATAL, PANIC
  format: common # json or common

# Access log configuration
accessLog: {} # Enable access logs