datatables:

    method:               POST # One of "GET"; "POST"

    # Default parameters to be passed to the template
    template_parameters:

        # Default class attribute to apply to the root table elements
        #className:        'table table-bordered'
        className:        'table'

